### ISSUE TITLE
[pipeline doc] umbrella ticket: Reverse engineer pipeline so it will be sustainable

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#507]
This is the umbrella ticket for the pipeline documentation effort. Close this ticket when:

- [ ] Code comments have been mostly completed [#497]
- [ ] Code has been made more sustainable with logging messages at debug, info, warn, err levels [#476]
- [ ] READMEs have been mostly fixed [#477]
- [ ] [User manual ](https://docs.google.com/document/d/1yA0bx-JnBZnLzPHj4s4kEEQlAO0V_-xpWgKMh_VWExk/edit)tickets #501, #502, #503, #504, #505 have been closed
